### ISSUE TITLE
I want to use this control for commercial usage 

### ISSUE THREAD

**Issue by forsubhi** [CoatedMoose/CustomViews#4]
is it possible to use your view in my commercial project?

**Comment by CoatedMoose** [comment]
Go for it. I'd love to know about the project, drop me the link when you launch and I will put it in the readme. I would also appreciate an attribution of some kind, but neither are required.

**Comment by forsubhi** [comment]
it is a project that will be connected to another project on PC (server) and get and send information to it. And it is dedicated for the companies that use the server project.I will tell you extra information when I finish it.by the way , thank you for your work ,and what is the easiest way to save the bitmap after drawing the signature.

**Comment by CoatedMoose** [comment]
To save to a jpeg, I would just do something like this 

`Bitmap bitmap = sigView.getImage();
FileOutputStream out = new FileOutputStream(fileLocation);
bitmap.compress(Bitmap.CompressFormat.JPEG, 100, out);`

But all you are doing is getting the bitmap backing the signature, so do whatever you want with it.
