### ISSUE TITLE
I added this two lines to your view to add a dot when the user click on signature view

### ISSUE THREAD

**Issue by forsubhi** [CoatedMoose/CustomViews#5]
private void touchDown(float x, float y) {
        mPath.reset();
        mPath.moveTo(x, y);
        curX = x;
        curY = y;
        //new 
        mPath.quadTo(curX, curY, curX+2, curY+ 2);
        mCanvas.drawPath(mPath, mPaint);
    }

**Comment by CoatedMoose** [comment]
I am not entirely sure why this is necessary. I thought I did last night, but then I fell asleep. Can you please elaborate?

**Comment by forsubhi** [comment]
when the user sign they often want to but dots in their signature so this code is important

**Comment by CoatedMoose** [comment]
Makes perfect sense. I don't think it is a good idea to draw a point for every single touchDown when the following drag will overwrite it. This will keep the drawing down. Negligible performance difference I am sure, but it appeals to my anal-retentiveness.
