### ISSUE TITLE
load previously created signature from file

### ISSUE THREAD

**Issue by virtualvoid** [CoatedMoose/CustomViews#6]
is this possible ?
thanks

**Comment by CoatedMoose** [comment]
Currently it is not. If you just want to show a previously created signature, you should be able to use an imageview and show the file in that. Maybe I misunderstand your intention though - what is it you were hoping to use a feature like that for?

**Comment by CoatedMoose** [comment]
I would be happy to reopen this issue at some point, or accept a pull request. This could be done by allowing ability to set the off-screen bitmap with the stored signature. You would need to be careful about matching sizes of old bitmap and the new bitmap. I am not sure what the best way of handling different sized bitmaps would be.
