### ISSUE TITLE
Can not clear sing

### ISSUE THREAD

**Issue by itvignes09** [CoatedMoose/CustomViews#7]
wow its a great app. but, i can not clear the signature, can you please help me?

**Comment by CoatedMoose** [comment]
Are you talking about the demo app? Or in your own app? What Android version?

**Comment by itvignes09** [comment]
i am asking about demo app only, i can put sgn in that given view its super, now i need to clear sign when i put wrong sign,

i need button click coding to clear the sign

```
    btnClearSign.setOnClickListener(new OnClickListener() {
        @Override
        public void onClick(View v) {
            // code to clear sign??????????
        }
    });
```

Thanks in advance

**Comment by CoatedMoose** [comment]
There was a method already to do that called `clearSig`, however I think short forming it is perhaps a silly notion. I have created a method called `clearSignature` that does the same thing and marked `clearSig` as deprecated.

**Comment by itvignes09** [comment]
First of all thank you for your reply.
No no its not silly notion, I already used signature.clearSig(); method. it makes "black" background of signature. so, i can not sing again.

```
    btnClearSign.setOnClickListener(new OnClickListener() {
        @Override
        public void onClick(View v) {
            // TODO Auto-generated method stub
            signature.clearSig();
        }
    });
```

**Comment by itvignes09** [comment]
Hi friend, are you there???????

**Comment by CoatedMoose** [comment]
Sorry, I have been really busy with school and haven't had a chance to look into it.

If you can let me know a bit more about the code you are working with that would be helpful.

The Android version (target and min)
device (which one?) or emulator
the theme you are using (holo, holo.light, sherlock etc).

**Comment by itvignes09** [comment]
okay okay 

Android min 8; target version 17 
Device : tablet model no accenote android version 4.0.4
Theme : theme.light

**Comment by CoatedMoose** [comment]
Try the latest version of you still have problems we can reopen.

**Comment by itvignes09** [comment]
we also tried latest version that 4.2 and 4.3.
but, its not working

**Comment by CoatedMoose** [comment]
When I said the latest version, I meant the latest version of this library. I was able to reproduce the bug you mentioned and corrected it. Sorry if that wasn't clear.

**Comment by itvignes09** [comment]
okay okay new library working well, but now i get background as white instead of transparent while saving the image
